prefect-sqlalchemy
PrefectHQ/prefect-recipes pull request #206
Opened 2023-02-22 11:00 UTC by sidharth1805

## Description

What's cooking? 
This PR adds a recipe for using Prefect with SQL alchemy.
Issue #149 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## New Recipe Checklist

- [x] My PR is in the format of `Add <project-name> recipe`
- [x] My recipe is reproducible and explains everything needed to run successfully. If my code has external dependencies, I make mention of them.
- [x] My code is easily understandable and/or well-commented.

2023-02-22 15:09 UTC, serinamarie commented
Hi @sidharth1805, welcome to prefect-recipes 🧑‍🍳 and congrats on your first contribution! We'll review this very soon 🙂

2023-02-22 15:10 UTC, sidharth1805 commented
Thank you @serinamarie waiting to get added 😃

2023-02-22 16:21 UTC, zzstoatzz requested changes
Thanks for contributing @sidharth1805!

I think I'd recommend removing all the files that are copied from the `prefect-sqlalchemy` docs - you could add a link to these docs.

Your flow (flows-advanced/prefect-sqlalchemy/etl_with_sql_alchemy.py) is awesome!

2023-02-22 16:21 UTC, zzstoatzz commented on flows-advanced/prefect-sqlalchemy/Sync.py
> +sqlalchemy_flow("BLOCK-NAME-PLACEHOLDER")
same as above

2023-02-22 16:21 UTC, zzstoatzz commented on flows-advanced/prefect-sqlalchemy/README.md
> +```
this appears to be the [landing page](https://prefecthq.github.io/prefect-sqlalchemy/) for prefect-sqlalchemy, which I don't think we need to include here

2023-02-22 16:21 UTC, zzstoatzz commented on flows-advanced/prefect-sqlalchemy/Examples_Catalog/README.md
> +    ```
i dont think we want to copy the [Examples Catalog](https://prefecthq.github.io/prefect-sqlalchemy/examples_catalog/) from `prefect-sqlalchemy` here - is there a real world use case you have that's inspired by these examples that you'd like to share?

2023-02-22 16:21 UTC, zzstoatzz commented on flows-advanced/prefect-sqlalchemy/Async.py
> +asyncio.run(sqlalchemy_flow("BLOCK-NAME-PLACEHOLDER"))
same as others

2023-02-22 16:21 UTC, zzstoatzz commented on flows-advanced/prefect-sqlalchemy/Blocks_Catalog/README.md
> +
same as others

2023-02-22 17:03 UTC, sidharth1805 commented
@zzstoatzz Have changed the requested

2023-02-22 17:55 UTC, ahuang11 requested changes
Thanks for contributing a recipe for SQLAlchemy! Left comments on optimizing the code.

2023-02-22 17:55 UTC, ahuang11 commented on flows-advanced/prefect-sqlalchemy/etl_with_sql_alchemy.py
> +    print(f"Logging Subflow for: {table_name}")
I don't think this is needed.

2023-02-22 17:55 UTC, ahuang11 commented on flows-advanced/prefect-sqlalchemy/etl_with_sql_alchemy.py
> +@flow(name="Ingest Data")
```suggestion
@flow(name="Ingest Data", log_prints=True)
```

2023-02-22 17:55 UTC, ahuang11 commented on flows-advanced/prefect-sqlalchemy/etl_with_sql_alchemy.py
> +    log_subflow(table_name)
```suggestion
```

2023-02-22 17:55 UTC, ahuang11 commented on flows-advanced/prefect-sqlalchemy/etl_with_sql_alchemy.py
> +    csv_url = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz"
Maybe this can be a CONSTANT_VARIABLE at the top.

2023-02-22 17:55 UTC, ahuang11 commented on flows-advanced/prefect-sqlalchemy/etl_with_sql_alchemy.py
> +        df.to_sql(name=table_name, con=engine, if_exists='append')
```suggestion
        df.to_sql(name=table_name, con=engine, if_exists='replace')
```

2023-02-22 17:55 UTC, ahuang11 commented on flows-advanced/prefect-sqlalchemy/etl_with_sql_alchemy.py
> +    df_iter = pd.read_csv(csv_name, iterator=True, chunksize=100000)
I don't think it's necessary to wget first. `pd.read_csv` can read from URLs directly
```suggestion
    df = pd.read_csv(url, compression="gzip")
```

2023-02-22 17:55 UTC, ahuang11 commented on flows-advanced/prefect-sqlalchemy/etl_with_sql_alchemy.py
> +    df = next(df_iter)
Since it can fit in memory I think we can remove this.
```suggestion
```

2023-02-22 17:55 UTC, ahuang11 commented on flows-advanced/prefect-sqlalchemy/README.md
> +This recipe demonstrates how to integrate prefect with SQL Alchemy.The prefect-sqlalchemy collection makes it easy to connect to a database in your Prefect flows.
```suggestion
This recipe demonstrates how to integrate Prefect with SQLAlchemy. The prefect-sqlalchemy collection makes it easy to connect to a database in your Prefect flows.
```

2023-02-22 18:16 UTC, sidharth1805 commented
@ahuang11 Please check now 😃

2023-02-22 18:33 UTC, sidharth1805 commented on flows-advanced/prefect-sqlalchemy/etl_with_sql_alchemy.py
> +import os
Removed

2023-02-22 18:34 UTC, sidharth1805 commented on flows-advanced/prefect-sqlalchemy/etl_with_sql_alchemy.py
> +import os
@ahuang11 Please check now

2023-02-22 18:55 UTC, sidharth1805 commented
@ahuang11 removed the os library can we run the workflows now 🙂

2023-02-22 19:06 UTC, ahuang11 commented
Thanks! It looks good to me. Was wondering if we should put this in beginner flows?

2023-02-22 19:07 UTC, sidharth1805 commented
@ahuang11 Sure it would be great 🙂

2023-02-22 19:09 UTC, sidharth1805 commented
Can I change then?

2023-02-22 19:09 UTC, ahuang11 commented
Yes

2023-02-22 19:13 UTC, sidharth1805 commented
@ahuang11 Moved please check now

2023-02-22 19:27 UTC, zzstoatzz commented
@sidharth1805 thanks for making these changes, looking good!

one last request from me, since you have `log_prints=True` on the flow, you don't need it on the tasks within that flow, since the tasks will inherit the `log_prints=True` setting - so can we take that out of the decorator for each task?

2023-02-22 19:34 UTC, sidharth1805 commented
@zzstoatzz Done Please check

2023-02-22 19:45 UTC, zzstoatzz approved these changes
thanks for the contribution - lgtm!

2023-02-24 18:58 UTC, merged

2023-02-24 19:00 UTC, serinamarie commented
@sidharth1805 Thanks for creating this recipe! Please reach out to [swag@prefect.io](mailto:swag@prefect.io) for your swag! 🧢